changelog:
  categories:
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Performance Improvements
      labels:
        - performance
    - title: Other Changes
      labels:
        - '*'
