image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .venv

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - python --version ; pip --version # For debugging
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install .

test:
  stage: test
  script:
    - source .venv/bin/activate
    - cd tests
    - python3 -m pytest .
  needs:
    - install

build:
  stage: deploy
  script:
    - source .venv/bin/activate
    - pip install .[all] repairwheel build
    - python3 -m build -w -o .cache/dist
    - python3 -m build -s -o dist
    - repairwheel .cache/dist/*.whl -o dist
    - twine check dist/*
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG_MESSAGE == "release"

  artifacts:
    paths:
      - dist/*

deploy:
  stage: deploy
  script:
    - echo "deploying!"
    - source .venv/bin/activate
    - twine upload dist/* --username __token__ --password $CI_TWINE_TOKEN
  rules:
    - when: manual
  dependencies:
    - build
