image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .venv

stages:
  # - install
  # - test
  - deploy

# install:
#   stage: install
#   script:
#     - python --version ; pip --version # For debugging
#     - python -m venv .venv
#     - source .venv/bin/activate
#     - pip install .

# test:
#   stage: test
#   script:
#     - source .venv/bin/activate
#     - cd tests
#     - python3 -m pytest .
#   needs:
#     - install

deploy:
  stage: deploy
  script:
    - echo "deploying!"
    - source .venv/bin/activate
    - pip install .[ci]
    - python3 -m build -w -o .cache/dist
    - python3 -m build -s -o dist
    - repairwheel .cache/dist/*.whl -o dist
    - twine check dist/*
    - twine upload dist/* --username __token__ --password $CI_TWINE_TOKEN
  rules:
    - when: manual
  artifacts:
    paths:
      - dist/*
    when: on_success
    expire_in: 1 month
