from __future__ import annotations

from pybes3.detectors.cgem import (
    cgem_gid_to_is_vstrip,
    cgem_gid_to_is_xstrip,
    cgem_gid_to_layer,
    cgem_gid_to_sheet,
    cgem_gid_to_strip,
    cgem_gid_to_strip_type,
    get_cgem_gid,
    parse_cgem_gid,
)
from pybes3.detectors.emc import (
    emc_barrel_h1,
    emc_barrel_h2,
    emc_barrel_h3,
    emc_barrel_l,
    emc_barrel_offset_1,
    emc_barrel_offset_2,
    emc_barrel_r,
    emc_gid_to_center_x,
    emc_gid_to_center_y,
    emc_gid_to_center_z,
    emc_gid_to_front_center_x,
    emc_gid_to_front_center_y,
    emc_gid_to_front_center_z,
    emc_gid_to_part,
    emc_gid_to_phi,
    emc_gid_to_point_x,
    emc_gid_to_point_y,
    emc_gid_to_point_z,
    emc_gid_to_theta,
    get_emc_crystal_position,
    get_emc_gid,
    parse_emc_gid,
)
from pybes3.detectors.mdc import (
    get_mdc_gid,
    get_mdc_wire_position,
    mdc_gid_to_east_x,
    mdc_gid_to_east_y,
    mdc_gid_to_east_z,
    mdc_gid_to_is_stereo,
    mdc_gid_to_layer,
    mdc_gid_to_stereo,
    mdc_gid_to_superlayer,
    mdc_gid_to_west_x,
    mdc_gid_to_west_y,
    mdc_gid_to_west_z,
    mdc_gid_to_wire,
    mdc_gid_z_to_x,
    mdc_gid_z_to_y,
    mdc_layer_to_is_stereo,
    mdc_layer_to_superlayer,
    parse_mdc_gid,
)
from pybes3.detectors.tof import (
    get_tof_gid,
    parse_tof_gid,
    tof_gid_to_layer_or_module,
    tof_gid_to_part,
    tof_gid_to_phi_or_strip,
)

__all__ = [
    # cgem
    "cgem_gid_to_is_vstrip",
    "cgem_gid_to_is_xstrip",
    "cgem_gid_to_layer",
    "cgem_gid_to_sheet",
    "cgem_gid_to_strip",
    "cgem_gid_to_strip_type",
    "get_cgem_gid",
    "parse_cgem_gid",
    # mdc
    "get_mdc_gid",
    "get_mdc_wire_position",
    "mdc_gid_to_east_x",
    "mdc_gid_to_east_y",
    "mdc_gid_to_east_z",
    "mdc_gid_to_is_stereo",
    "mdc_gid_to_layer",
    "mdc_gid_to_stereo",
    "mdc_gid_to_superlayer",
    "mdc_gid_to_west_x",
    "mdc_gid_to_west_y",
    "mdc_gid_to_west_z",
    "mdc_gid_to_wire",
    "mdc_gid_z_to_x",
    "mdc_gid_z_to_y",
    "mdc_layer_to_is_stereo",
    "mdc_layer_to_superlayer",
    "parse_mdc_gid",
    # tof
    "get_tof_gid",
    "parse_tof_gid",
    "tof_gid_to_layer_or_module",
    "tof_gid_to_part",
    "tof_gid_to_phi_or_strip",
    # emc
    "emc_barrel_h1",
    "emc_barrel_h2",
    "emc_barrel_h3",
    "emc_barrel_l",
    "emc_barrel_offset_1",
    "emc_barrel_offset_2",
    "emc_barrel_r",
    "emc_gid_to_center_x",
    "emc_gid_to_center_y",
    "emc_gid_to_center_z",
    "emc_gid_to_front_center_x",
    "emc_gid_to_front_center_y",
    "emc_gid_to_front_center_z",
    "emc_gid_to_part",
    "emc_gid_to_phi",
    "emc_gid_to_point_x",
    "emc_gid_to_point_y",
    "emc_gid_to_point_z",
    "emc_gid_to_theta",
    "get_emc_crystal_position",
    "get_emc_gid",
    "parse_emc_gid",
]
