from __future__ import annotations

import numpy as np

# detectors/cgem.cc
def get_cgem_idx(layer, sheet, strip_type, strip): ...
def cgem_idx_to_layer(idx): ...
def cgem_idx_to_sheet(idx): ...
def cgem_idx_to_strip_type(idx): ...
def cgem_idx_to_strip(idx): ...
def cgem_idx_to_is_xstrip(idx): ...
def cgem_idx_to_is_vstrip(idx): ...

# detectors/mdc.cc
def _init_mdc_geom(
    east_x: np.ndarray,
    east_y: np.ndarray,
    east_z: np.ndarray,
    west_x: np.ndarray,
    west_y: np.ndarray,
    west_z: np.ndarray,
): ...
def get_mdc_idx(layer, wire): ...
def mdc_idx_to_superlayer(idx): ...
def mdc_layer_to_superlayer(layer): ...
def mdc_idx_to_layer(idx): ...
def mdc_idx_to_wire(idx): ...
def mdc_idx_to_stereo(idx): ...
def mdc_layer_to_is_stereo(layer): ...
def mdc_idx_to_is_stereo(idx): ...
def mdc_idx_to_west_x(idx): ...
def mdc_idx_to_west_y(idx): ...
def mdc_idx_to_west_z(idx): ...
def mdc_idx_to_east_x(idx): ...
def mdc_idx_to_east_y(idx): ...
def mdc_idx_to_east_z(idx): ...
def mdc_idx_z_to_x(idx, z): ...
def mdc_idx_z_to_y(idx, z): ...

# detectors/tof.cc
def get_tof_idx(part, layer_or_module, phi_or_strip): ...
def tof_idx_to_part(idx): ...
def tof_idx_to_layer_or_module(idx): ...
def tof_idx_to_phi_or_strip(idx): ...
def tof_hit_status_to_is_raw(status): ...
def tof_hit_status_to_is_readout(status): ...
def tof_hit_status_to_is_counter(status): ...
def tof_hit_status_to_is_cluster(status): ...
def tof_hit_status_to_is_barrel(status): ...
def tof_hit_status_to_is_east(status): ...
def tof_hit_status_to_layer(status): ...
def tof_hit_status_to_is_overflow(status): ...
def tof_hit_status_to_is_multihit(status): ...
def tof_hit_status_to_n_counter(status): ...
def tof_hit_status_to_n_east(status): ...
def tof_hit_status_to_n_west(status): ...
def tof_hit_status_to_is_mrpc(status): ...

# detectors/emc.cc
def _init_emc_geom(
    points_x: np.ndarray,
    points_y: np.ndarray,
    points_z: np.ndarray,
    center_x: np.ndarray,
    center_y: np.ndarray,
    center_z: np.ndarray,
    front_center_x: np.ndarray,
    front_center_y: np.ndarray,
    front_center_z: np.ndarray,
): ...
def get_emc_idx(part, theta, phi): ...
def emc_idx_to_part(idx): ...
def emc_idx_to_theta(idx): ...
def emc_idx_to_phi(idx): ...
def emc_idx_to_center_x(idx): ...
def emc_idx_to_center_y(idx): ...
def emc_idx_to_center_z(idx): ...
def emc_idx_to_front_center_x(idx): ...
def emc_idx_to_front_center_y(idx): ...
def emc_idx_to_front_center_z(idx): ...
def emc_idx_to_point_x(idx, point): ...
def emc_idx_to_point_y(idx, point): ...
def emc_idx_to_point_z(idx, point): ...

# helix.cc
def dr_phi0_to_x(dr, phi0): ...
def dr_phi0_to_y(dr, phi0): ...
def phi0_to_phi(phi0): ...
def kappa_to_pt(kappa): ...
def kappa_to_charge(kappa): ...
def kappa_to_radius(kappa): ...
def _fix_dr_sign(dr, phi0, dist_phi): ...

# identifier.cc
## mdc
def check_mdc_id(mdc_id): ...
def mdc_id_to_wire(mdc_id): ...
def mdc_id_to_layer(mdc_id): ...
def mdc_id_to_is_stereo(mdc_id): ...
def get_mdc_id(wire, layer, wire_type): ...

## tof
def check_tof_id(tof_id): ...
def tof_id_to_part(tof_id): ...
def tof_id_to_end(tof_id): ...
def _tof_id_to_layer_or_module_1(tof_id): ...
def _tof_id_to_layer_or_module_2(tof_id, part): ...
def _tof_id_to_phi_or_strip_1(tof_id): ...
def _tof_id_to_phi_or_strip_2(tof_id, part): ...
def get_tof_id(part, layer_or_module, phi_or_strip, end): ...

## emc
def check_emc_id(emc_id): ...
def emc_id_to_module(emc_id): ...
def emc_id_to_theta(emc_id): ...
def emc_id_to_phi(emc_id): ...
def get_emc_id(module, theta, phi): ...

## muc
def check_muc_id(muc_id): ...
def muc_id_to_part(muc_id): ...
def muc_id_to_segment(muc_id): ...
def muc_id_to_layer(muc_id): ...
def muc_id_to_channel(muc_id): ...
def get_muc_id(part, segment, layer, channel): ...

## cgem
def check_cgem_id(cgem_id): ...
def cgem_id_to_layer(cgem_id): ...
def cgem_id_to_sheet(cgem_id): ...
def cgem_id_to_strip_type(cgem_id): ...
def cgem_id_to_strip(cgem_id): ...
def get_cgem_id(layer, sheet, strip_type, strip): ...
