name: Build wheels

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build-wheels:
        runs-on: ${{ matrix.os }}
        name: Build wheels on ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
                os: [ubuntu-latest, windows-latest, macos-latest]
    
        steps:
        - uses: actions/checkout@v4
    
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
    
        - name: Build wheels for ${{ matrix.os }}-${{ matrix.python-version }}
          shell: pwsh
          run: |
            python -m pip install --upgrade pip
            python -m pip install repairwheel build
            python -m build -w -o .cache/dist
            Get-ChildItem -Path .cache/dist -Recurse
            repairwheel .cache/dist/*.whl -o dist/
            Get-ChildItem -Path dist -Recurse

        - name: Upload distributions
          uses: actions/upload-artifact@v4
          with:
                name: ci-wheels-${{ matrix.os }}-${{ matrix.python-version }}
                path: dist/*.whl
    
    build-sdist:
        name: Build source distribution
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Build sdist
          run: pipx run build --sdist

        - uses: actions/upload-artifact@v4
          with:
            name: ci-sdist
            path: dist/*.tar.gz