name: Make docs and deploy to GitHub Pages

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        name: Build and deploy
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: pip install .[docs]

            - name: Checkout gh-pages branch
              run: |
                git fetch origin gh-pages:gh-pages
                git checkout gh-pages
                git pull origin gh-pages

            - name: Build documentation
              run: mkdocs gh-deploy --force
